import {StyleSheet} from 'react-native';
import colors from '../../styles/colors';
import iPhoneSize from '../../utils/display';

let headingTextSize = 30;
if (iPhoneSize() === 'small') {
  headingTextSize = 26;
}

const styles = StyleSheet.create({
  wrapper: {
    display: 'flex',
    flex: 1,
    backgroundColor: colors.colmenaBackground,
  },
  scrollViewWrapper: {
    flex: 1,
    padding: 0,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: colors.colmenaBackground,
  },
  scrollView: {
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 8,
    flex: 1,
  },
  brand: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 40,
  },
  brandText: {
    fontFamily: 'Montserrat-Medium',
    fontWeight: '300',
    fontSize: headingTextSize,
    color: colors.colmenaGrey,
    marginLeft:30,
  },
  brandTextAlt: {
    fontFamily: 'Montserrat-Medium',
    fontWeight: '300',
    fontSize: 23,
    color: colors.colmenaGrey,
    marginLeft:40,
  },
  brandTextCenter: {
    fontFamily: 'Montserrat-Medium',
    fontWeight: '300',
    fontSize: 22,
    margin: 5,
    color: colors.colmenaGrey,
    textAlign:'center',
  },
  headerImage: {
    resizeMode: 'contain',
    alignContent: 'center',
    alignSelf:'center',
    width: '100%',
    marginTop: 10,
    marginBottom:10,

  },
  colmenaLogo: {
    resizeMode: 'stretch',
    marginRight: 10,
  },
  titleImg: {
    resizeMode: 'stretch',
    marginRight: 10,
    width:40,
    height: 40,
  },
  notificationWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  btnSubmit: {
    width: '100%',
    backgroundColor: colors.colmenaGreen,
    borderRadius: 5,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  btnSubmitSec: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 5,
    borderColor: colors.colmenaGreen,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    marginBottom: 10,
    borderWidth: 2,
  },
  btnSubmitDisabled: {
    width: '100%',
    backgroundColor: colors.colmenaGreenDisabled,
    borderRadius: 5,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  wrapperCenter: {
    alignContent: 'center',
    alignItems: 'center',
  },
  submitText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    fontWeight: '900',
  },
  submitSecText: {
    color: colors.colmenaGreen,
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    fontWeight: '900',
  },
  headerTitle: {
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    fontSize: 24,
    color: colors.colmenaGrey,
  },
  title: {
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    color: colors.colmenaGrey02,
  },
  text: {
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    color: '#212121',
  },
  tableHeader: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 0,
    marginBottom: 10,
    width: '100%',
    paddingTop: 10,
    paddingBottom: 0,
  },
  tableGroup: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    width: '100%',
    backgroundColor: colors.colmenaUltraLightGrey,
  },
  tableItem: {
    alignItems: 'center',
    width: '30%',
  },
  footText: {
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    fontWeight: '900',
    margin: 5,
    color: colors.colmenaOtherGreen,
  },
  footTotal: {
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    margin: 10,
    color: colors.colmenaGreen,
  },
  tableFoot: {
    flex: 3,
    width: '90%',
    alignSelf: 'stretch',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  headerMsg: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 0,
    marginBottom: 0,
    width: '100%',
    paddingTop: 0,
    paddingBottom: 0,
  },
  headerText: {
    width: '85%',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    fontSize: 22,
    color: colors.colmenaGrey,
  },
  headerIcon: {
    resizeMode: 'stretch',
    marginRight: 10,
    width: 46,
    height: 46,
  },
  headerBox: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 0,
    marginBottom: 10,
    paddingTop: 10,
    paddingBottom: 10,
  },
  box: {
    borderRadius: 5,
    backgroundColor: colors.colmenaUltraLightGrey,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 0,
    marginBottom: 10,
    width: '100%',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 30,
  },
  groupLine: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  boxLine: {
    width: '50%',
    padding: 5,
  },
  headerSubtitle: {
    marginBottom: 10,
  },
  titleLine: {
    fontFamily: 'Montserrat-Medium',
    color: colors.colmenaTitleLine,
    fontWeight: 'bold',
  },
  textLine: {
    fontFamily: 'Montserrat-Medium',
    color: colors.colmenaTextLine,
  },
  boxImage: {
    resizeMode: 'contain',
    padding: 10,
    width: 40,
    height: 40,
  },
  amount: {
    width: '20%',
    textAlign: 'center',
    justifyContent: 'center',
  },
  countText: {
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    color: colors.colmenaGrey02,
  },
  amountText: {
    fontFamily: 'Montserrat-Medium',
    textAlign: 'right',
    color: '#212121',
  },
  wasteCode: {
    backgroundColor: colors.white,
    fontFamily: 'Montserrat-Medium',
    borderRadius: 5,
    padding: 3,
    marginBottom: 6,
  },
  activityIndicator: {
    flex: 1,
    alignItems: 'center',
  },
  totalize: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.colmenaUltraLightGrey,
    paddingLeft: 20,
    paddingRight: 30,
    paddingTop: 12,
    paddingBottom: 12,
    marginBottom: 10,
  },
  input: {
    flex: 1,
    textAlign: 'center',
  },
  btnSubmit: {
    width: '100%',
    backgroundColor: colors.colmenaGreen,
    borderRadius: 5,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  submitText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    fontWeight: '900',
  },
});

export default styles;
